export const CAPTURE = 'capture'; //拍照
export const CAPTURE_IMG = 'captureImg'; //拍照图片
export const CAPTURE_SCREEN = 'captureScreen'; //拍照当前页面
export const CAPTURE_SECTION = 'captureSection'; // 截取局部
export const CAPTURE_SECTION_DONE = 'captureSectionDone'; // 截取局部
export const NEWTABLE = 'newtab'; //新窗口
export const GETINDEXEDDB = 'getIndexedDb'; //新窗口
export const VIDEOSTART = 'videoStart';
export const VIDEOSTOP = 'videoStop';
export const VIDEOPAUSE = 'pauseVideo';
export const RECORDER = 'Recorder';
export const VIDEORESUME = 'resumeVideo';
export const PROGRESS = 'progress';
export const STOP_CAPTURE = 'stopCapture';
export const POPSTATUS = 'popupStatus';
export const VIDEOSTATUS = 'videoStatus';
export const GETPOPSTATUS = 'getpopupstatus';
export const GETVIDEOTIMER = 'getvideotimer';
export const GETVIDEOSTATUS = 'getvideostatus';
export const SET_PAGE_ENV = 'setPageEnv';
